package edu.study.dao;

import edu.study.model.Administrator;
import java.util.List;

public interface AdministratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int insert(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    Administrator selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    List<Administrator> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int updateByPrimaryKey(Administrator record);
}