package edu.study.dao;

import edu.study.model.ArticleCategory;
import java.util.List;

public interface ArticleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int insert(ArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    ArticleCategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    List<ArticleCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int updateByPrimaryKey(ArticleCategory record);

}