package edu.study.dao;

import edu.study.model.ArticleKeyword;
import java.util.List;

import edu.study.model.Keyword;
import org.apache.ibatis.annotations.Param;

public interface ArticleKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_keyword
     *
     * @mbg.generated Tue Feb 11 10:46:44 CST 2020
     */
    int deleteByPrimaryKey(@Param("articleId") Integer articleId, @Param("keyword") String keyword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_keyword
     *
     * @mbg.generated Tue Feb 11 10:46:44 CST 2020
     */
    int insert(ArticleKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_keyword
     *
     * @mbg.generated Tue Feb 11 10:46:44 CST 2020
     */
    ArticleKeyword selectByPrimaryKey(@Param("articleId") Integer articleId, @Param("keyword") String keyword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_keyword
     *
     * @mbg.generated Tue Feb 11 10:46:44 CST 2020
     */
    List<ArticleKeyword> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_keyword
     *
     * @mbg.generated Tue Feb 11 10:46:44 CST 2020
     */
    int updateByPrimaryKey(ArticleKeyword record);


    // 选择某篇文章的所有关键词表
    List<Keyword> selectByArticleId(Integer articleId);

    // 批量操作，对于每个 (articleId,keyword) 如果不存在就插入，如果存在就更新
    void replaceInto(@Param("articleId")Integer articleId,@Param("keywordList")List<Keyword> keywordList);
}