package edu.study.dao;

import edu.study.model.Article;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int deleteByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    Article selectByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    List<Article> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int updateByPrimaryKey(Article record);

    int insertAndGetId(Article article);

    int articleCountByCategoryId(Integer categoryId);

    List<Article> selectByPageLimit(Map<String,Object> mp);

    int updateArticleClicks(Integer articleId);// 文章点击数加一

    int updateArticleAgrees(Integer articleId);// 文章点赞数加一
}