package edu.study.dao;

import edu.study.model.ArticleRecommend;
import java.util.List;

import edu.study.model.Keyword;
import org.apache.ibatis.annotations.Param;

public interface ArticleRecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_recommend
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    int deleteByPrimaryKey(@Param("username") String username, @Param("articleId") Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_recommend
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    int insert(ArticleRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_recommend
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    ArticleRecommend selectByPrimaryKey(@Param("username") String username, @Param("articleId") Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_recommend
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    List<ArticleRecommend> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_recommend
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    int updateByPrimaryKey(ArticleRecommend record);

    int deleteByUsername(String username);

    int insertList(List<ArticleRecommend> list);

    List<Integer> selectByUsername(String username);

}