package edu.study.dao;

import edu.study.model.ArticleCollection;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_collection
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int deleteByPrimaryKey(@Param("username") String username, @Param("articleId") Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_collection
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int insert(ArticleCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_collection
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    ArticleCollection selectByPrimaryKey(@Param("username") String username, @Param("articleId") Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_collection
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    List<ArticleCollection> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_collection
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int updateByPrimaryKey(ArticleCollection record);

    Integer countByArticleId(Integer articleId);

    Integer countByUsername(String username);
}