package edu.study.dao;

import edu.study.model.ArticleAgree;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleAgreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_agree
     *
     * @mbg.generated Tue Feb 11 10:46:44 CST 2020
     */
    int deleteByPrimaryKey(@Param("username") String username, @Param("articleId") Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_agree
     *
     * @mbg.generated Tue Feb 11 10:46:44 CST 2020
     */
    int insert(ArticleAgree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_agree
     *
     * @mbg.generated Tue Feb 11 10:46:44 CST 2020
     */
    ArticleAgree selectByPrimaryKey(@Param("username") String username, @Param("articleId") Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_agree
     *
     * @mbg.generated Tue Feb 11 10:46:44 CST 2020
     */
    List<ArticleAgree> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_agree
     *
     * @mbg.generated Tue Feb 11 10:46:44 CST 2020
     */
    int updateByPrimaryKey(ArticleAgree record);

    Integer countByArticleId(Integer articleId);

    Integer countByUsername(String username);

    List<ArticleAgree> selectByTime(Date date);
}