package edu.study.dao;

import edu.study.model.VideoCollection;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_collection
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int deleteByPrimaryKey(@Param("username") String username, @Param("videoId") Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_collection
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int insert(VideoCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_collection
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    VideoCollection selectByPrimaryKey(@Param("username") String username, @Param("videoId") Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_collection
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    List<VideoCollection> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_collection
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    int updateByPrimaryKey(VideoCollection record);
}