package edu.study.dao;

import edu.study.model.WordCollection;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_collection
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    int deleteByPrimaryKey(@Param("username") String username, @Param("wordName") String wordName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_collection
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    int insert(WordCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_collection
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    WordCollection selectByPrimaryKey(@Param("username") String username, @Param("wordName") String wordName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_collection
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    List<WordCollection> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_collection
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    int updateByPrimaryKey(WordCollection record);

    int countByUsername(String username);
}