package edu.study.dao;

import edu.study.model.WordRecited;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordRecitedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_recited
     *
     * @mbg.generated Fri Feb 14 09:17:17 CST 2020
     */
    int deleteByPrimaryKey(@Param("username") String username, @Param("wordName") String wordName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_recited
     *
     * @mbg.generated Fri Feb 14 09:17:17 CST 2020
     */
    int insert(WordRecited record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_recited
     *
     * @mbg.generated Fri Feb 14 09:17:17 CST 2020
     */
    WordRecited selectByPrimaryKey(@Param("username") String username, @Param("wordName") String wordName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_recited
     *
     * @mbg.generated Fri Feb 14 09:17:17 CST 2020
     */
    List<WordRecited> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_recited
     *
     * @mbg.generated Fri Feb 14 09:17:17 CST 2020
     */
    int updateByPrimaryKey(WordRecited record);

    int countByPrimaryKey(@Param("username")String username,@Param("wordName")String wordName);

    int replace(WordRecited record);

    int countByUsername(String username);
}