package edu.study.model;

public class Administrator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.NAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.PASSWORD
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.PHONE_NUMBER
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String phoneNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.NAME
     *
     * @return the value of administrator.NAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.NAME
     *
     * @param name the value for administrator.NAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.PASSWORD
     *
     * @return the value of administrator.PASSWORD
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.PASSWORD
     *
     * @param password the value for administrator.PASSWORD
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.PHONE_NUMBER
     *
     * @return the value of administrator.PHONE_NUMBER
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.PHONE_NUMBER
     *
     * @param phoneNumber the value for administrator.PHONE_NUMBER
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }
}