package edu.study.model;

import java.util.Date;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ARTICLE_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.USERNAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.CATEGORY_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.NAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.CREATE_TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.MODIFY_TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.LABEL
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.CLICKS
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Integer clicks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.AGREES
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Integer agrees;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.CONTENT
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ARTICLE_ID
     *
     * @return the value of article.ARTICLE_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ARTICLE_ID
     *
     * @param articleId the value for article.ARTICLE_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.USERNAME
     *
     * @return the value of article.USERNAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.USERNAME
     *
     * @param username the value for article.USERNAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.CATEGORY_ID
     *
     * @return the value of article.CATEGORY_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.CATEGORY_ID
     *
     * @param categoryId the value for article.CATEGORY_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.NAME
     *
     * @return the value of article.NAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.NAME
     *
     * @param name the value for article.NAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.CREATE_TIME
     *
     * @return the value of article.CREATE_TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.CREATE_TIME
     *
     * @param createTime the value for article.CREATE_TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.MODIFY_TIME
     *
     * @return the value of article.MODIFY_TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.MODIFY_TIME
     *
     * @param modifyTime the value for article.MODIFY_TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.LABEL
     *
     * @return the value of article.LABEL
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.LABEL
     *
     * @param label the value for article.LABEL
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.CLICKS
     *
     * @return the value of article.CLICKS
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Integer getClicks() {
        return clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.CLICKS
     *
     * @param clicks the value for article.CLICKS
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setClicks(Integer clicks) {
        this.clicks = clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.AGREES
     *
     * @return the value of article.AGREES
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Integer getAgrees() {
        return agrees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.AGREES
     *
     * @param agrees the value for article.AGREES
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setAgrees(Integer agrees) {
        this.agrees = agrees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.CONTENT
     *
     * @return the value of article.CONTENT
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.CONTENT
     *
     * @param content the value for article.CONTENT
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}