package edu.study.model;

public class ArticleRecommend {

    /**
     *  构造函数
     */
    public ArticleRecommend(String u,Integer a,Double s){
        username = u;
        articleId = a;
        similarity = s;
    }
    public ArticleRecommend(){}

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_recommend.USERNAME
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_recommend.ARTICLE_ID
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_recommend.SIMILARITY
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    private Double similarity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_recommend.USERNAME
     *
     * @return the value of article_recommend.USERNAME
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_recommend.USERNAME
     *
     * @param username the value for article_recommend.USERNAME
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_recommend.ARTICLE_ID
     *
     * @return the value of article_recommend.ARTICLE_ID
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_recommend.ARTICLE_ID
     *
     * @param articleId the value for article_recommend.ARTICLE_ID
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_recommend.SIMILARITY
     *
     * @return the value of article_recommend.SIMILARITY
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    public Double getSimilarity() {
        return similarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_recommend.SIMILARITY
     *
     * @param similarity the value for article_recommend.SIMILARITY
     *
     * @mbg.generated Wed Feb 12 08:59:43 CST 2020
     */
    public void setSimilarity(Double similarity) {
        this.similarity = similarity;
    }
}