package edu.study.model;

public class ArticleCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.CATEGORY_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_category.NAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.CATEGORY_ID
     *
     * @return the value of article_category.CATEGORY_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.CATEGORY_ID
     *
     * @param categoryId the value for article_category.CATEGORY_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_category.NAME
     *
     * @return the value of article_category.NAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_category.NAME
     *
     * @param name the value for article_category.NAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}