package edu.study.model;

import java.util.Date;

public class ArticleCollection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_collection.USERNAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_collection.ARTICLE_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_collection.TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_collection.USERNAME
     *
     * @return the value of article_collection.USERNAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_collection.USERNAME
     *
     * @param username the value for article_collection.USERNAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_collection.ARTICLE_ID
     *
     * @return the value of article_collection.ARTICLE_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_collection.ARTICLE_ID
     *
     * @param articleId the value for article_collection.ARTICLE_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_collection.TIME
     *
     * @return the value of article_collection.TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_collection.TIME
     *
     * @param time the value for article_collection.TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}