package edu.study.model;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.ARTICLE_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.USERNAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.CREATE_TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.REF_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Integer refId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.CONTENT
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.COMMENT_ID
     *
     * @return the value of comment.COMMENT_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.COMMENT_ID
     *
     * @param commentId the value for comment.COMMENT_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.ARTICLE_ID
     *
     * @return the value of comment.ARTICLE_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.ARTICLE_ID
     *
     * @param articleId the value for comment.ARTICLE_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.USERNAME
     *
     * @return the value of comment.USERNAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.USERNAME
     *
     * @param username the value for comment.USERNAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.CREATE_TIME
     *
     * @return the value of comment.CREATE_TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.CREATE_TIME
     *
     * @param createTime the value for comment.CREATE_TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.REF_ID
     *
     * @return the value of comment.REF_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Integer getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.REF_ID
     *
     * @param refId the value for comment.REF_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.CONTENT
     *
     * @return the value of comment.CONTENT
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.CONTENT
     *
     * @param content the value for comment.CONTENT
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}