package edu.study.model;

import java.util.Date;

public class Video {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.VIDEO_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Integer videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.VIDEO_NAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String videoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.VIDEO_ADDRESS
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String videoAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.DESCRIPTION
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.LABEL
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.CREATE_TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.VIDEO_ID
     *
     * @return the value of video.VIDEO_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.VIDEO_ID
     *
     * @param videoId the value for video.VIDEO_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.VIDEO_NAME
     *
     * @return the value of video.VIDEO_NAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.VIDEO_NAME
     *
     * @param videoName the value for video.VIDEO_NAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.VIDEO_ADDRESS
     *
     * @return the value of video.VIDEO_ADDRESS
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getVideoAddress() {
        return videoAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.VIDEO_ADDRESS
     *
     * @param videoAddress the value for video.VIDEO_ADDRESS
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setVideoAddress(String videoAddress) {
        this.videoAddress = videoAddress == null ? null : videoAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.DESCRIPTION
     *
     * @return the value of video.DESCRIPTION
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.DESCRIPTION
     *
     * @param description the value for video.DESCRIPTION
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.LABEL
     *
     * @return the value of video.LABEL
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.LABEL
     *
     * @param label the value for video.LABEL
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.CREATE_TIME
     *
     * @return the value of video.CREATE_TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.CREATE_TIME
     *
     * @param createTime the value for video.CREATE_TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}