package edu.study.model;

import java.util.Date;

public class VideoCollection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_collection.USERNAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_collection.VIDEO_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Integer videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_collection.TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_collection.USERNAME
     *
     * @return the value of video_collection.USERNAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_collection.USERNAME
     *
     * @param username the value for video_collection.USERNAME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_collection.VIDEO_ID
     *
     * @return the value of video_collection.VIDEO_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_collection.VIDEO_ID
     *
     * @param videoId the value for video_collection.VIDEO_ID
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_collection.TIME
     *
     * @return the value of video_collection.TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_collection.TIME
     *
     * @param time the value for video_collection.TIME
     *
     * @mbg.generated Fri Jan 17 14:50:36 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}