package edu.study.model;

import java.util.Date;

public class WordCollection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_collection.USERNAME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_collection.WORD_NAME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    private String wordName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_collection.TIME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_collection.USERNAME
     *
     * @return the value of word_collection.USERNAME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_collection.USERNAME
     *
     * @param username the value for word_collection.USERNAME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_collection.WORD_NAME
     *
     * @return the value of word_collection.WORD_NAME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public String getWordName() {
        return wordName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_collection.WORD_NAME
     *
     * @param wordName the value for word_collection.WORD_NAME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public void setWordName(String wordName) {
        this.wordName = wordName == null ? null : wordName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_collection.TIME
     *
     * @return the value of word_collection.TIME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_collection.TIME
     *
     * @param time the value for word_collection.TIME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}