package edu.study.model;

import java.util.Date;

public class WordRecited {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_recited.USERNAME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_recited.WORD_NAME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    private String wordName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_recited.REPEAT
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    private Integer repeat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_recited.LAST_RECITE
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    private Date lastRecite;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_recited.USERNAME
     *
     * @return the value of word_recited.USERNAME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_recited.USERNAME
     *
     * @param username the value for word_recited.USERNAME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_recited.WORD_NAME
     *
     * @return the value of word_recited.WORD_NAME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public String getWordName() {
        return wordName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_recited.WORD_NAME
     *
     * @param wordName the value for word_recited.WORD_NAME
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public void setWordName(String wordName) {
        this.wordName = wordName == null ? null : wordName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_recited.REPEAT
     *
     * @return the value of word_recited.REPEAT
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public Integer getRepeat() {
        return repeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_recited.REPEAT
     *
     * @param repeat the value for word_recited.REPEAT
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public void setRepeat(Integer repeat) {
        this.repeat = repeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_recited.LAST_RECITE
     *
     * @return the value of word_recited.LAST_RECITE
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public Date getLastRecite() {
        return lastRecite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_recited.LAST_RECITE
     *
     * @param lastRecite the value for word_recited.LAST_RECITE
     *
     * @mbg.generated Tue Jan 21 10:57:41 CST 2020
     */
    public void setLastRecite(Date lastRecite) {
        this.lastRecite = lastRecite;
    }
}