package edu.study.model;

public class Word {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.WORD_NAME
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    private String wordName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.WORD_TYPE
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    private Integer wordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.VOICE_ADDRESS
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    private String voiceAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.PICTURE_ADDRESS
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    private String pictureAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.WORD_TRANSLATE
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    private String wordTranslate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.WORD_EXAMPLE
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    private String wordExample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.EXAMPLE_TRANSLATE
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    private String exampleTranslate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word.SITUATION
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    private String situation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.WORD_NAME
     *
     * @return the value of word.WORD_NAME
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public String getWordName() {
        return wordName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.WORD_NAME
     *
     * @param wordName the value for word.WORD_NAME
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public void setWordName(String wordName) {
        this.wordName = wordName == null ? null : wordName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.WORD_TYPE
     *
     * @return the value of word.WORD_TYPE
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public Integer getWordType() {
        return wordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.WORD_TYPE
     *
     * @param wordType the value for word.WORD_TYPE
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public void setWordType(Integer wordType) {
        this.wordType = wordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.VOICE_ADDRESS
     *
     * @return the value of word.VOICE_ADDRESS
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public String getVoiceAddress() {
        return voiceAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.VOICE_ADDRESS
     *
     * @param voiceAddress the value for word.VOICE_ADDRESS
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public void setVoiceAddress(String voiceAddress) {
        this.voiceAddress = voiceAddress == null ? null : voiceAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.PICTURE_ADDRESS
     *
     * @return the value of word.PICTURE_ADDRESS
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public String getPictureAddress() {
        return pictureAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.PICTURE_ADDRESS
     *
     * @param pictureAddress the value for word.PICTURE_ADDRESS
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public void setPictureAddress(String pictureAddress) {
        this.pictureAddress = pictureAddress == null ? null : pictureAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.WORD_TRANSLATE
     *
     * @return the value of word.WORD_TRANSLATE
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public String getWordTranslate() {
        return wordTranslate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.WORD_TRANSLATE
     *
     * @param wordTranslate the value for word.WORD_TRANSLATE
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public void setWordTranslate(String wordTranslate) {
        this.wordTranslate = wordTranslate == null ? null : wordTranslate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.WORD_EXAMPLE
     *
     * @return the value of word.WORD_EXAMPLE
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public String getWordExample() {
        return wordExample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.WORD_EXAMPLE
     *
     * @param wordExample the value for word.WORD_EXAMPLE
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public void setWordExample(String wordExample) {
        this.wordExample = wordExample == null ? null : wordExample.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.EXAMPLE_TRANSLATE
     *
     * @return the value of word.EXAMPLE_TRANSLATE
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public String getExampleTranslate() {
        return exampleTranslate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.EXAMPLE_TRANSLATE
     *
     * @param exampleTranslate the value for word.EXAMPLE_TRANSLATE
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public void setExampleTranslate(String exampleTranslate) {
        this.exampleTranslate = exampleTranslate == null ? null : exampleTranslate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word.SITUATION
     *
     * @return the value of word.SITUATION
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public String getSituation() {
        return situation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word.SITUATION
     *
     * @param situation the value for word.SITUATION
     *
     * @mbg.generated Tue Jan 21 10:57:40 CST 2020
     */
    public void setSituation(String situation) {
        this.situation = situation == null ? null : situation.trim();
    }
}